services:

  ########################################
  ### Identus Cloud Agent & PRISM Node ###
  ########################################

  db:
    image: postgres:13
    network_mode: "host"
    environment:
      POSTGRES_MULTIPLE_DATABASES: "pollux,connect,agent,node_db"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data_db:/var/lib/postgresql/data
      - ./dbs/postgres-init-script.sh:/docker-entrypoint-initdb.d/init-script.sh
      - ./dbs/postgres-max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "agent" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prism-node:
    image: docker.io/inputoutput/prism-node:2.6.0
    network_mode: "host"
    environment:
      NODE_PSQL_HOST: localhost:5432
    depends_on:
      db:
        condition: service_healthy

  cloud-agent:
    image: docker.io/hyperledgeridentus/identus-cloud-agent:2.2.0
    network_mode: "host"
    environment:
      POLLUX_DB_HOST: localhost
      POLLUX_DB_PORT: 5432
      POLLUX_DB_NAME: pollux
      POLLUX_DB_USER: postgres
      POLLUX_DB_PASSWORD: postgres
      CONNECT_DB_HOST: localhost
      CONNECT_DB_PORT: 5432
      CONNECT_DB_NAME: connect
      CONNECT_DB_USER: postgres
      CONNECT_DB_PASSWORD: postgres
      AGENT_DB_HOST: localhost
      AGENT_DB_PORT: 5432
      AGENT_DB_NAME: agent
      AGENT_DB_USER: postgres
      AGENT_DB_PASSWORD: postgres
      PRISM_NODE_HOST: localhost
      PRISM_NODE_PORT: 50053
      POLLUX_STATUS_LIST_REGISTRY_PUBLIC_URL: http://localhost:8085/cloud-agent
      DIDCOMM_SERVICE_URL: http://localhost:3000/didcomm
      REST_SERVICE_URL: http://localhost:8085/cloud-agent
      SECRET_STORAGE_BACKEND: postgres
      DEV_MODE: true
      API_KEY_ENABLED: false
    depends_on:
      db:
        condition: service_healthy
      prism-node:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/_system/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  ################
  ### MEDIATOR ###
  ################

  mongo:
    image: mongo:6.0
    network_mode: "host"
    command: [ "--auth" ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=mediator
    volumes:
      - ./dbs/mongo-initdb.js:/docker-entrypoint-initdb.d/initdb.js

  identus-mediator:
    image: docker.io/hyperledgeridentus/identus-mediator:1.2.1
    network_mode: "host"
    environment:
      # Creates the identity:
      # These keys are for demo purpose only for production deployments generate keys
      # Please follow the README file for guidelines on How to generate JWK format keys
      # KEY_AGREEMENT KEY_AUTHENTICATION are using format JOSE(JWK) OKP type base64urlsafe encoded keys
      - KEY_AGREEMENT_D=Z6D8LduZgZ6LnrOHPrMTS6uU2u5Btsrk1SGs4fn8M7c
      - KEY_AGREEMENT_X=Sr4SkIskjN_VdKTn0zkjYbhGTWArdUNE4j_DmUpnQGw
      - KEY_AUTHENTICATION_D=INXCnxFEl0atLIIQYruHzGd5sUivMRyQOzu87qVerug
      - KEY_AUTHENTICATION_X=MBjnXZxkMcoQVVL21hahWAw43RuAG-i64ipbeKKqwoA
      - SERVICE_ENDPOINTS=http://localhost:8080;ws://localhost:8080/ws
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_PROTOCOL=mongodb
      - MONGODB_HOST=localhost
      - MONGODB_PORT=27017
      - MONGODB_DB_NAME=mediator
    depends_on:
      - "mongo"

volumes:
  pg_data_db:
