name: File Hygiene

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    uses: hyperledger-identus/.github/.github/workflows/lint-files.yml@b5e934e6d44ea4ff18db76f9eae0405ee4378bd6 # main
